name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: S1r4i3
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push snake to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.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 }}
          publish_dir: ./dist
          publish_branch: output
